// Easy Ship API (India-specific pickup scheduling). Field names below follow
// Amazon's published Easy Ship API reference at the time this was written;
// verify against the current reference before pointing this at a real
// seller account — see docs/AMAZON_SETUP.md.
import { hostForRegion } from '../endpoints.js';
import { spApiRequest } from '../http.js';

const EASY_SHIP_API_VERSION = '2022-03-23';

function baseUrl(region, { sandbox = false } = {}) {
  return `https://${hostForRegion(region, { sandbox })}/easyShip/${EASY_SHIP_API_VERSION}`;
}

/** Available pickup windows for a marketplace + package weight. */
export async function listHandoverSlots(account, refreshToken, { amazonOrderId, packageDetails }, options = {}) {
  const data = await spApiRequest({
    accountKey: account.id,
    operation: 'easyShipListSlots',
    method: 'POST',
    url: `${baseUrl(account.region, { sandbox: options.sandbox })}/timeSlot`,
    refreshToken,
    data: {
      marketplaceId: options.amazonMarketplaceId,
      amazonOrderId,
      packageDetails,
    },
  });
  return data;
}

/**
 * Book the pickup. `idempotencyKey` (rule R4) is passed as a header so a
 * retried call cannot double-schedule — the caller generates it deterministically.
 */
export async function createScheduledPackage(account, refreshToken, { amazonOrderId, packageDetails, slotId, idempotencyKey }, options = {}) {
  const data = await spApiRequest({
    accountKey: account.id,
    operation: 'easyShipSchedule',
    method: 'POST',
    url: `${baseUrl(account.region, { sandbox: options.sandbox })}/package`,
    refreshToken,
    data: {
      marketplaceId: options.amazonMarketplaceId,
      amazonOrderId,
      packageDetails,
      scheduledPackageId: { slotId },
      // Not all Easy Ship deployments accept a client idempotency header; a
      // deterministic key is still generated by the caller as the primary
      // defence (the shipments.idempotency_key UNIQUE constraint), this is
      // belt-and-braces where Amazon does honour it.
      clientReferenceId: idempotencyKey,
    },
  });
  return data;
}

/** Reschedule (new slot) or cancel (status: Cancelled) an already-booked package. */
export async function updateScheduledPackages(account, refreshToken, { amazonOrderId, updates }, options = {}) {
  const data = await spApiRequest({
    accountKey: account.id,
    operation: 'easyShipSchedule',
    method: 'PATCH',
    url: `${baseUrl(account.region, { sandbox: options.sandbox })}/package`,
    refreshToken,
    data: { marketplaceId: options.amazonMarketplaceId, amazonOrderId, updates },
  });
  return data;
}

/** Fetches the label/invoice document URLs for an already-scheduled package. */
export async function getLabel(account, refreshToken, { amazonOrderId }, options = {}) {
  const data = await spApiRequest({
    accountKey: account.id,
    operation: 'easyShipSchedule',
    method: 'GET',
    url: `${baseUrl(account.region, { sandbox: options.sandbox })}/documents`,
    refreshToken,
    params: { marketplaceId: options.amazonMarketplaceId, amazonOrderId },
  });
  return data;
}
