import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateDashboardMetrics, inclusiveDays } from './dashboard-calculations.js';
const range={start:'2026-06-27T00:00:00Z',end:'2026-07-27T00:00:00Z'};
const line=(id,description,amount,parent='Order',extra={})=>({settlement_id:'statement',source_row_id:id,source_row_key:id,report_document_id:'doc-statement',amount_description:description,amount,parent_transaction_type:parent,posted_date:'2026-07-10T00:00:00Z',...extra});
function mindcircusFixture(){return{
  orders:[{amazon_order_id:'shipped',status:'Shipped',raw:{history:'was Unshipped and Pending'}},{amazon_order_id:'cancelled',status:'Cancelled'},{amazon_order_id:'replacement',status:'Replacement'}],
  orderItems:[{source_row_id:'db1',amazon_order_id:'shipped',sku:'same',asin:'a',quantity_ordered:2,raw:{orderItemId:'item-1',QuantityOrdered:2}},{source_row_id:'db2',amazon_order_id:'shipped',sku:'same',asin:'a',quantity_ordered:3,raw:{orderItemId:'item-2',QuantityOrdered:3}}],
  returns:[{source_row_id:'ret1',order_id:'shipped',sku:'same',return_date:'2026-07-12',quantity:2,raw:{eventId:'event-1'}}],
  settlementRows:[
    line('sf-sale','Principal',164084.08,'Order'),line('sf-refund','Principal',-45927.15,'Refund'),line('fba-sale','Principal',49861.08,'Order'),line('fba-refund','Principal',-10996.61,'Refund'),
    line('promo','Promotional rebate',-2955.62),line('promo-refund','Promotional rebate refund',457.02,'Refund'),line('safe','SAFE-T Reimbursement',196.72,'SAFE-T Reimbursement'),line('inventory','FBA inventory credit',921.78),line('shipping','Shipping credits',934.22),line('shipping-refund','Shipping credit refund',-169.50,'Refund'),
    line('fees','Selling fees',-56358.40,'ServiceFee'),line('fee-refund','Selling fee refunds',7397.65,'ServiceFeeRefund'),line('tds','TCS/TDS withholding',-1469.30,'Withholding'),
    line('gst-collected','Product Tax GST collected',38146.06),line('gst-refund','Product Tax GST refund',-10194.50,'Refund')
  ],
  scopedSettlementIds:['statement'],
  settlementDocuments:[{report_id:'report-statement',report_document_id:'doc-statement',row_count:15,settlement_ids:['statement'],imported_at:'2026-07-28T00:00:00Z'}],settlementSyncJobs:[{status:'completed'}],
  financeItems:[line('partial','Principal',999,'Order',{report_document_id:null})],
  settlementHeaders:[{settlement_id:'statement',report_document_id:'doc-statement',deposit_date:'27.07.2026 00:00:00 UTC',total_amount:133927.53},{settlement_id:'transfer',report_document_id:'doc-transfer',deposit_date:'20.07.2026 17:22:30 UTC',total_amount:131801.69},{settlement_id:'failed',report_document_id:'doc-failed',deposit_date:'2026-07-21T00:00:00Z',total_amount:500,transaction_type:'Failed transfer'}],
  reimbursements:[{sku:'duplicate-fallback',amount:999,reimbursement_date:'2026-07-10'}]
};}
test('matches the MINDCIRCUS Amazon Account Activity fixture without constants',()=>{
  const r=calculateDashboardMetrics(mindcircusFixture(),range);
  assert.equal(r.metrics.netSales.value,154522.8);assert.equal(r.statement.income.value,156406.02);
  assert.equal(r.metrics.deductions.value,50430.05);assert.equal(r.metrics.deductions.components.find(x=>x.category==='tcs_tds').amount,1469.3);assert.equal(r.metrics.deductions.components.find(x=>x.category==='operational_fees').amount,48960.75);
  assert.equal(r.metrics.reimbursements.value,196.72);assert.equal(r.statement.tax.value,0);assert.equal(r.statement.gst.value,27951.56);
  assert.equal(r.metrics.settled.value,131801.69);assert.equal(r.statement.transfers.value,-131801.69);assert.equal(r.statement.expenses.value,-50430.05);
  assert.equal(r.metrics.drr.value,5150.76);assert.equal(Number(r.metrics.feeImpact.value.toFixed(2)),22.88);assert.equal(Number(r.metrics.refundValueRate.value.toFixed(2)),26.61);
  assert.equal(r.diagnostics.sourceComplete,true);assert.equal(r.diagnostics.categoryTotals.operatingActivity,133927.53);assert.equal(r.diagnostics.categoryTotals.residual,2125.84);
});
test('uses current status only and preserves identical-SKU lines with stable item IDs',()=>{const r=calculateDashboardMetrics(mindcircusFixture(),range);assert.equal(r.metrics.netQty.value,3);assert.equal(r.metrics.orders.value,1);assert.equal(r.metrics.returnRate.value,40);});
test('negative Principal is a refund through parent transaction metadata',()=>{const input=mindcircusFixture();const refund=input.settlementRows.find(x=>x.source_row_id==='sf-refund');delete refund.transaction_type;assert.equal(calculateDashboardMetrics(input,range).metrics.netSales.value,154522.8);});
test('missing return quantity makes quantity KPIs unavailable instead of guessing one',()=>{const input=mindcircusFixture();input.returns[0].quantity=null;const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.returns.value,null);assert.equal(r.metrics.netQty.value,null);assert.equal(r.metrics.returnRate.value,null);assert.equal(r.metrics.returnRate.status,'Unavailable / source mismatch');});
test('positive returns with unavailable shipped source never report zero percent',()=>{const input=mindcircusFixture();input.orderItems=[];const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.returnRate.value,null);assert.match(r.metrics.returnRate.status,/source mismatch/);});
test('removes duplicate reports and finance summary rows, and uses one reimbursement source',()=>{const input=mindcircusFixture();input.settlementRows.push({...input.settlementRows[0],source_row_id:'duplicate-db-id'});input.financeItems.push({transaction_id:'x',category:'summary_amazon_fees',amount:-999,posted_date:'2026-07-10'});const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.netSales.value,154522.8);assert.equal(r.metrics.reimbursements.value,196.72);assert.ok(r.diagnostics.duplicateRows>0);});
test('GST invoice value uses genuine documents, credit notes, mixed rates and stable document keys',()=>{const input=mindcircusFixture();input.gstInvoices=[{source_row_id:'1',taxable_value:100,raw:{'document-number':'INV1','line-item-id':'1','document-type':'Invoice','gst-rate':18}},{source_row_id:'dup',taxable_value:100,raw:{'document-number':'INV1','line-item-id':'1','document-type':'Invoice','gst-rate':18}},{source_row_id:'2',taxable_value:40,raw:{'document-number':'CN1','line-item-id':'1','document-type':'Credit Note','gst-rate':5}},{source_row_id:'synthetic',taxable_value:999,raw:{}}];assert.equal(calculateDashboardMetrics(input,range).metrics.gstValue.value,60);});
test('GST invoice value is unavailable without genuine imported invoices',()=>{const r=calculateDashboardMetrics({...mindcircusFixture(),gstInvoices:[{taxable_value:381909.1,raw:{}}]},range);assert.equal(r.metrics.gstValue.value,null);assert.equal(r.metrics.gstValue.status,'Unavailable');});
test('derives half-open range days and excludes failed/out-of-range deposits',()=>{const input=mindcircusFixture();input.settlementHeaders.push({settlement_id:'outside',deposit_date:'2026-07-27T00:00:00Z',total_amount:1000});const r=calculateDashboardMetrics(input,range);assert.equal(inclusiveDays(range.start,range.end),30);assert.equal(r.metrics.settled.value,131801.69);});

test('refuses partial settlement imports and reports the missing settlement ID',()=>{const input=mindcircusFixture();input.settlementDocuments=[];const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.netSales.value,null);assert.equal(r.metrics.netSales.status,'Incomplete source data');assert.deepEqual(r.diagnostics.missingSettlementIds,['statement']);});
test('loads multiple settlements and preserves legitimate identical-value source rows',()=>{const input=mindcircusFixture();const extra=line('same-value','Shipping credits',10,'Order',{settlement_id:'second',report_document_id:'doc-second'});input.settlementRows.push(extra);input.scopedSettlementIds.push('second');input.settlementDocuments.push({report_id:'r2',report_document_id:'doc-second',row_count:1,settlement_ids:['second'],imported_at:'2026-07-28T00:00:00Z'});input.settlementHeaders.push({settlement_id:'second',report_document_id:'doc-second',deposit_date:'2026-07-27T00:00:00Z',total_amount:10});const r=calculateDashboardMetrics(input,range);assert.equal(r.diagnostics.sourceComplete,true);assert.equal(r.statement.income.value,156416.02);});
test('sums several successful DD.MM.YYYY UTC deposits in the half-open range',()=>{const input=mindcircusFixture();input.settlementHeaders.push({settlement_id:'transfer-2',report_document_id:'doc-transfer-2',deposit_date:'26.07.2026 23:59:59 UTC',total_amount:100});const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.settled.value,131901.69);assert.equal(r.statement.transfers.value,-131901.69);});

test('validates a full settlement with all rows but scopes KPI rows by posted date',()=>{const input=mindcircusFixture();input.settlementRows.push(line('outside-row','Principal',100,'Order',{posted_date:'2026-06-26T23:59:59Z'}));input.settlementHeaders.find(row=>row.settlement_id==='statement').total_amount+=100;const r=calculateDashboardMetrics(input,range);assert.equal(r.diagnostics.sourceComplete,true);assert.equal(r.diagnostics.settlementChecks[0].detailTotal,134027.53);assert.equal(r.metrics.netSales.value,154522.8);});
test('distinguishes missing deposit data from a confirmed zero-transfer period',()=>{const missing=mindcircusFixture();missing.settlementHeaders.find(row=>row.settlement_id==='statement').deposit_date=null;let r=calculateDashboardMetrics(missing,range);assert.equal(r.metrics.settled.value,null);assert.equal(r.metrics.settled.status,'Unavailable / deposit data missing');assert.equal(r.statement.transfers.status,'Incomplete source data');const zero=mindcircusFixture();zero.settlementHeaders=zero.settlementHeaders.filter(row=>row.settlement_id==='statement');r=calculateDashboardMetrics(zero,range);assert.equal(r.metrics.settled.value,0);assert.equal(r.statement.transfers.value,0);});
test('classifies missing headers and duplicate downloads in settlement diagnostics',()=>{const missing=mindcircusFixture();missing.settlementHeaders=[];let r=calculateDashboardMetrics(missing,range);assert.equal(r.diagnostics.settlementChecks[0].classification,'detail rows without header');const duplicate=mindcircusFixture();duplicate.settlementDocuments.push({...duplicate.settlementDocuments[0],report_document_id:'older-doc'});r=calculateDashboardMetrics(duplicate,range);assert.deepEqual(r.diagnostics.settlementChecks[0].duplicateDocumentIds,['older-doc']);});

test('retry wrapper retries incomplete report import failures',async()=>{
  const {runJob}=await import('./runner.js');let attempts=0;
  const value=await runJob('settlement-import',async()=>{attempts++;if(attempts<3)throw new Error('incomplete document');return 'complete';},3);
  assert.equal(value,'complete');assert.equal(attempts,3);
});
