import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateDashboardMetrics, inclusiveDays } from './dashboard-calculations.js';
import { classifyAccountActivityRow } from './account-activity-classification.js';
import { zonedCalendarInstant } from './marketplace-time.js';
const range={start:'2026-06-26T18:30:00.000Z',end:'2026-07-26T18:30:00.000Z'};
const line=(id,description,amount,parent='Order',extra={})=>({settlement_id:'statement',source_row_id:id,source_line_hash:id,amount_description:description,amount,parent_transaction_type:parent,posted_date:'2026-07-10T00:00:00Z',...extra});
function mindcircusFixture(){return{
  context:{sellerId:'fixture-seller',marketplaceId:'fixture-india-marketplace',marketplaceTimezone:'Asia/Kolkata',region:'IN'},sourceCompleteness:{settlementCoverageComplete:true,financesCoverageComplete:false,ordersCoverageComplete:true,orderItemsCoverageComplete:true,returnsCoverageComplete:true,gstCoverageComplete:true,transferCoverageComplete:true},
  settlementControls:[{settlement_id:'statement',report_id:'fixture-report',document_id:'fixture-document',header_total_minor:13180169,detail_total_minor:13180169,control_difference_minor:0,completeness_status:'complete'}],
  orders:[{amazon_order_id:'shipped',status:'Shipped',raw:{history:'was Unshipped and Pending'}},{amazon_order_id:'cancelled',status:'Cancelled'},{amazon_order_id:'replacement',status:'Replacement'}],
  orderItems:[{source_row_id:'db1',amazon_order_id:'shipped',sku:'same',asin:'a',quantity_ordered:2,raw:{orderItemId:'item-1'}},{source_row_id:'db2',amazon_order_id:'shipped',sku:'same',asin:'a',quantity_ordered:3,raw:{orderItemId:'item-2'}}],
  returns:[{source_row_id:'ret1',order_id:'shipped',sku:'same',return_date:'2026-07-12',quantity:2,raw:{eventId:'event-1'}}],
  settlementRows:[
    line('sf-sale','Principal',164084.08,'Order'),line('sf-refund','Principal',-45927.15,'Refund'),line('fba-sale','Principal',49861.08,'Order'),line('fba-refund','Principal',-10996.61,'Refund'),
    line('promo','Promotional rebate',-2955.62),line('promo-refund','Promotional rebate refund',457.02,'Refund'),line('safe','SAFE-T Reimbursement',196.72,'SAFE-T Reimbursement'),line('shipping','Shipping credits',1686.50),line('shipping-refund','Shipping refund',-169.50,'Refund'),line('inventory-credit','FBA inventory credit',169.50,'other-transaction'),
    line('fees','Selling fees',-56358.40,'ServiceFee'),line('fee-refund','Selling fee refunds',7397.65,'ServiceFeeRefund'),line('tds','TCS/TDS withholding',-1469.30,'Withholding'),
    line('gst-collected','Product Tax GST collected',38146.06),line('gst-refund','Product Tax GST refund',-10194.50,'Refund'),line('prior-period-control','Prior period settlement balance',-2125.84,'other-transaction',{posted_date:'2026-06-26T18:29:59.999Z'})
  ],
  financeItems:[line('partial','Principal',999,'Order')],
  settlementHeaders:[{settlement_id:'statement',deposit_date:'2026-07-20T00:00:00Z',total_amount:131801.69},{settlement_id:'failed',deposit_date:'2026-07-21T00:00:00Z',total_amount:500,transaction_type:'Failed transfer'}],
  reimbursements:[{sku:'duplicate-fallback',amount:999,reimbursement_date:'2026-07-10'}]
};}
test('matches the MINDCIRCUS Amazon Account Activity fixture without constants',()=>{
  const r=calculateDashboardMetrics(mindcircusFixture(),range);
  assert.equal(r.metrics.netSales.value,154522.8);assert.equal(r.statement.income.value,156406.02);
  assert.equal(r.metrics.deductions.value,50430.05);assert.equal(r.metrics.deductions.components.find(x=>x.category==='tcs_tds').amount,1469.3);assert.equal(r.metrics.deductions.components.find(x=>x.category==='operational_fees').amount,48960.75);
  assert.equal(r.metrics.reimbursements.value,196.72);assert.equal(r.statement.tax.value,0);assert.equal(r.statement.gst.value,27951.56);
  assert.equal(r.metrics.settled.value,131801.69);assert.equal(r.statement.transfers.value,-131801.69);assert.equal(r.statement.expenses.value,-50430.05);
  assert.equal(r.metrics.drr.value,5150.76);assert.equal(Number(r.metrics.feeImpact.value.toFixed(2)),22.88);assert.equal(Number(r.metrics.refundValueRate.value.toFixed(2)),26.61);
  assert.deepEqual([r.statement.income.evidence.debit,r.statement.income.evidence.credit],[60048.88,216454.9]);assert.deepEqual([r.statement.expenses.evidence.debit,r.statement.expenses.evidence.credit],[57827.7,7397.65]);
  assert.equal(r.accountActivityControl.closingMovement,2125.84);
  assert.equal(r.diagnostics.sourcePolicy.financial.startsWith('Amazon V2 Settlement report'),true);
});
test('uses current status only and preserves identical-SKU lines with stable item IDs',()=>{const r=calculateDashboardMetrics(mindcircusFixture(),range);assert.equal(r.metrics.netQty.value,3);assert.equal(r.metrics.orders.value,1);assert.equal(r.metrics.returnRate.value,40);});
test('negative Principal is a refund through parent transaction metadata',()=>{const input=mindcircusFixture();const refund=input.settlementRows.find(x=>x.source_row_id==='sf-refund');delete refund.transaction_type;assert.equal(calculateDashboardMetrics(input,range).metrics.netSales.value,154522.8);});
test('missing return quantity makes quantity KPIs unavailable instead of guessing one',()=>{const input=mindcircusFixture();input.returns[0].quantity=null;const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.returns.value,null);assert.equal(r.metrics.netQty.value,null);assert.equal(r.metrics.returnRate.value,null);assert.equal(r.metrics.returnRate.status,'unavailable');});
test('positive returns with unavailable shipped source never report zero percent',()=>{const input=mindcircusFixture();input.orderItems=[];const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.returnRate.value,null);assert.equal(r.metrics.returnRate.status,'unavailable');});
test('removes duplicate reports and finance summary rows, and uses one reimbursement source',()=>{const input=mindcircusFixture();input.settlementRows.push({...input.settlementRows[0],source_row_id:'duplicate-db-id'});input.financeItems.push({transaction_id:'x',category:'summary_amazon_fees',amount:-999,posted_date:'2026-07-10'});const r=calculateDashboardMetrics(input,range);assert.equal(r.metrics.netSales.value,154522.8);assert.equal(r.metrics.reimbursements.value,196.72);assert.ok(r.diagnostics.duplicateRows>0);});
test('GST invoice value uses genuine documents, credit notes, mixed rates and stable document keys',()=>{const input=mindcircusFixture();input.gstInvoices=[{source_row_id:'1',taxable_value:100,raw:{'document-number':'INV1','line-item-id':'1','document-type':'Invoice','gst-rate':18}},{source_row_id:'dup',taxable_value:100,raw:{'document-number':'INV1','line-item-id':'1','document-type':'Invoice','gst-rate':18}},{source_row_id:'2',taxable_value:40,raw:{'document-number':'CN1','line-item-id':'1','document-type':'Credit Note','gst-rate':5}},{source_row_id:'synthetic',taxable_value:999,raw:{}}];assert.equal(calculateDashboardMetrics(input,range).metrics.gstValue.value,60);});
test('GST invoice value is unavailable without genuine imported invoices',()=>{const r=calculateDashboardMetrics({...mindcircusFixture(),gstInvoices:[{taxable_value:381909.1,raw:{}}]},range);assert.equal(r.metrics.gstValue.value,null);assert.equal(r.metrics.gstValue.status,'unavailable');});
test('derives half-open range days and excludes failed/out-of-range deposits',()=>{const input=mindcircusFixture();input.settlementHeaders.push({settlement_id:'outside',deposit_date:'2026-07-27T00:00:00Z',total_amount:1000});const r=calculateDashboardMetrics(input,range);assert.equal(inclusiveDays(range.start,range.end),30);assert.equal(r.metrics.settled.value,131801.69);});
test('uses integer minor units and exposes unknown non-zero labels instead of silently treating them as income',()=>{const input=mindcircusFixture();input.settlementRows.push(line('unknown','Novel Amazon label',99.99,'Novel event',{amount_minor:10001}));const r=calculateDashboardMetrics(input,range);assert.equal(r.statement.income.value,null);assert.equal(r.diagnostics.status,'reconciliation_error');assert.equal(r.diagnostics.unmappedAmount,100.01);assert.equal(r.diagnostics.unmappedRows[0].source_row_id,'unknown');});
test('changes reference calculations when a source fixture row changes',()=>{const input=mindcircusFixture();input.settlementRows.find(row=>row.source_row_id==='sf-sale').amount+=0.01;const r=calculateDashboardMetrics(input,range);assert.equal(r.statement.income.value,156406.03);assert.equal(r.metrics.netSales.value,154522.81);});
test('filters financial posting instants at the midnight IST half-open boundary',()=>{const input=mindcircusFixture();input.settlementRows.push(line('before','Shipping credits',999,'Order',{posted_date:'2026-06-26T18:29:59.999Z'}));input.settlementRows.push(line('at-start','Shipping credits',1,'Order',{posted_date:'2026-06-26T18:30:00.000Z'}));input.settlementRows.push(line('at-end','Shipping credits',999,'Order',{posted_date:'2026-07-26T18:30:00.000Z'}));const r=calculateDashboardMetrics(input,range);assert.equal(r.statement.income.value,156407.02);assert.deepEqual(r.effectiveUtcRange,undefined);assert.equal(r.statement.income.marketplaceTimezone,'Asia/Kolkata');assert.deepEqual(r.statement.income.effectiveUtcRange,{start:range.start,endExclusive:range.end});});
test('never uses a partial settlement source or an unvalidated settlement control',()=>{const missing=mindcircusFixture();missing.sourceCompleteness.settlementCoverageComplete=false;let r=calculateDashboardMetrics(missing,range);assert.equal(r.statement.income.value,null);assert.equal(r.statement.income.status,'incomplete_source');const invalid=mindcircusFixture();invalid.settlementControls[0].control_difference_minor=1;invalid.settlementControls[0].completeness_status='reconciliation_error';r=calculateDashboardMetrics(invalid,range);assert.equal(r.statement.income.value,null);assert.equal(r.statement.income.status,'reconciliation_error');});
test('preserves legitimate identical-value source lines with different source hashes',()=>{const input=mindcircusFixture();input.settlementRows.push(line('same-a','Shipping credits',1));input.settlementRows.push(line('same-b','Shipping credits',1));const r=calculateDashboardMetrics(input,range);assert.equal(r.statement.income.value,156408.02);assert.equal(r.statement.income.includedRows.filter(row=>row.amount_description==='Shipping credits').length,3);});
test('separates customer GST, fee GST, and withholding using normalized source fields',()=>{const india={marketplaceId:'arbitrary',marketplaceTimezone:'Asia/Kolkata',region:'IN'};assert.equal(classifyAccountActivityRow({parent_transaction_type:'Order',amount_type:'ItemPrice',amount_description:'Product Tax',amount:-18},india).section,'gst');const fee=classifyAccountActivityRow({parent_transaction_type:'Order',amount_type:'ItemFees',amount_description:'Commission IGST',amount:-18},india);assert.equal(fee.section,'expenses');assert.equal(fee.feeGst,true);assert.equal(classifyAccountActivityRow({parent_transaction_type:'Refund',amount_type:'ItemTCS',amount_description:'TCS-IGST',amount:1},india).withholding,true);});
test('converts marketplace calendar dates to exact IST boundaries without seller-specific constants',()=>{assert.equal(zonedCalendarInstant('2026-06-27','Asia/Kolkata'),'2026-06-26T18:30:00.000Z');assert.equal(zonedCalendarInstant('2026-07-27','Asia/Kolkata'),'2026-07-26T18:30:00.000Z');});
