ALTER TABLE returns ADD COLUMN IF NOT EXISTS quantity int NOT NULL DEFAULT 1;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS raw jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE gst_invoices ADD COLUMN IF NOT EXISTS raw jsonb NOT NULL DEFAULT '{}'::jsonb;
