-- The inline UNIQUE(...) clauses declared alongside settlement_rows, returns,
-- order_items, and reimbursements in migration 001's CREATE TABLE IF NOT
-- EXISTS statements are still live constraints on any database where those
-- CREATE TABLE statements actually ran fresh - i.e. every new tenant's
-- database, unlike the specific production database exercised throughout
-- this session's testing, where these tables already existed *before*
-- migration 001 ran and so never picked up these constraints at all (that
-- gap is exactly why migration 013 had to backfill them as separately named
-- indexes in the first place).
--
-- Confirmed by testing against a brand-new database built from these
-- migrations: inserting two settlement_rows that are genuinely separate
-- transactions sharing identical business columns (a real, legitimate
-- scenario - e.g. two identically priced units refunded from the same
-- order-item on the same day) raises "duplicate key value violates unique
-- constraint settlement_rows_tenant_id_order_id_amount_type_amount_descr_key"
-- and aborts the sync outright. Migration 017 dropped the *separately
-- created* uq_settlement_rows_conflict/uq_returns_conflict/
-- uq_order_items_conflict indexes from migration 013, but never touched
-- these original, autogenerated-name constraints from migration 001 - a
-- different catalog object entirely - and never even considered
-- reimbursements, which has the exact same inline-UNIQUE pattern but was
-- never part of migration 013's table list to begin with.
--
-- source_key (migration 014) is the real row identity now. This drops every
-- remaining non-source_key unique constraint on these four tables via
-- pg_constraint rather than a guessed-at autogenerated name, since Postgres
-- truncates long inline constraint names unpredictably close to its 63-char
-- identifier limit and the exact name is not reliably known in advance.
DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT conrelid::regclass::text AS table_name, conname
    FROM pg_constraint
    WHERE contype = 'u'
      AND conrelid::regclass::text IN ('settlement_rows', 'returns', 'order_items', 'reimbursements')
      AND conname NOT LIKE 'uq\_%\_tenant\_source\_key'
  LOOP
    EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', rec.table_name, rec.conname);
  END LOOP;
END $$;
