-- gst_invoices never got the source_key treatment settlement_rows,
-- finance_transaction_items, returns, order_items, and reimbursements
-- already received in migrations 011/012/014 - its only identity has ever
-- been the inline UNIQUE(tenant_id, invoice_type, order_id, invoice_date)
-- from migration 001, with no line-item discriminator at all. A real
-- Merchant Tax Report has one row per SHIPMENT ITEM, not one per order, so
-- a two-SKU order invoiced on the same date produces two genuinely distinct
-- rows that composite key cannot tell apart - confirmed live, uploading one
-- real file: "69 row(s) in gst_invoices shared a conflict key within one
-- batch and were merged", i.e. real GST line items silently overwriting
-- each other. Worse, on at least one database (the one this was diagnosed
-- against) a source_key column already exists on gst_invoices - added
-- outside of any migration in this repo, NOT NULL with no default - so the
-- application code not supplying one crashed the insert outright (Postgres
-- 23502) rather than merging silently. This migration closes both gaps and
-- brings gst_invoices in line with how every other report table already
-- works, on any database regardless of which of those two states it is
-- currently in.
ALTER TABLE gst_invoices ADD COLUMN IF NOT EXISTS source_key text;

UPDATE gst_invoices
SET source_key = encode(digest(coalesce(order_id,'') || '|' || coalesce(invoice_type,'') || '|' || coalesce(invoice_date::text,'') || '|' || coalesce(taxable_value::text,'') || '|' || coalesce(cgst::text,'') || '|' || coalesce(sgst::text,'') || '|' || coalesce(igst::text,'') || '|' || id::text, 'sha256'), 'hex')
WHERE source_key IS NULL;

ALTER TABLE gst_invoices ALTER COLUMN source_key SET DEFAULT encode(gen_random_bytes(16), 'hex');
ALTER TABLE gst_invoices ALTER COLUMN source_key SET NOT NULL;

-- Real upsert identity from here on, same as the other five tables.
DELETE FROM gst_invoices a USING gst_invoices b
WHERE a.ctid < b.ctid AND a.tenant_id = b.tenant_id AND a.source_key = b.source_key;
CREATE UNIQUE INDEX IF NOT EXISTS uq_gst_invoices_tenant_source_key ON gst_invoices(tenant_id, source_key);

-- Drops the old composite UNIQUE(tenant_id, invoice_type, order_id,
-- invoice_date) - whether it's the inline constraint from migration 001
-- (on a database where that CREATE TABLE ran fresh) or the separately named
-- uq_gst_invoices_conflict index from migration 013 - by querying
-- pg_constraint directly rather than guessing an autogenerated name, same
-- technique migration 018 used for the other four tables. Left in place,
-- it would still reject a real two-SKU-same-day insert even though the
-- application's ON CONFLICT clause now targets source_key instead -
-- Postgres enforces every unique constraint on a table regardless of which
-- one a given INSERT's ON CONFLICT names.
DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT conname
    FROM pg_constraint
    WHERE contype = 'u'
      AND conrelid = 'gst_invoices'::regclass
      AND conname NOT LIKE 'uq\_gst\_invoices\_tenant\_source\_key'
  LOOP
    EXECUTE format('ALTER TABLE gst_invoices DROP CONSTRAINT %I', rec.conname);
  END LOOP;
END $$;
DROP INDEX IF EXISTS uq_gst_invoices_conflict;
